### PR TITLE
Automatically locate and use correct .jshintrc

### PR DESCRIPTION
**Pull request by carljm**
Currently, the `.jshintrc` support requires setting a global config var pointing to the location of the `.jshintrc` file. This adds an extra configuration step (currently not documented in the README), and makes it difficult to work on multiple different projects with different `.jshintrc` files.

Ideally, each time `flymake` is initialized on a new buffer, it would use the Emacs function `locate-dominating-file` to automatically find the nearest `.jshintrc` file in containing directories, and automatically use that `.jshintrc` for that buffer.

### CODE REVIEW

**Comment by carljm** [comment]
Hmm, just realized this is a dupe of #10. The code is quite a bit simpler, because it uses `locate-dominating-file` rather than reimplementing it, and it doesn't insert "home directory" as the automatic last step in the search. (I think in many cases people will be editing files in their home directory so this is unnecessary, it would be found by walking the filesystem anyway).

**Comment by wyuenho** [comment]
Yep this PR is much better. My PR is old and messy. I've submitted a much better one to flycheck.

**Comment by ralphtheninja** [comment]
+1 Please merge this @daleharvey

**Comment by crodjer** [comment]
+1 for merge.

**Comment by daleharvey** [comment]
:) Sorry about this, definitely useful

As you may have noticed I am not really doing a great job of maintaining this, it was mostly just written because I couldnt find anything better, is there a well maintained lib that does the same thing these days? (else if someone else wants to maintain this it would be awesome)

**Comment by crodjer** [comment]
Thanks @carljm and @daleharvey.
@daleharvey  couldn't find anything else better for this. There is https://github.com/jegbjerg/flymake-node-jshint, but I had trouble getting it to work.

**Pull request merged**
